### PR TITLE
add table style

### PR DESCRIPTION
**Pull request by Blacate**
The \<table\>\<\/table\> does not have a suitable style, so I add some class for the table.

**Previous screenshot**
before

**Modified screenshot**
after

### CODE REVIEW

**Comment by phoenixlzx** [comment]
Actually you can do it with themes

like this one [phoenixlzx/MinoriWiki-theme-semantic-ui](https://github.com/phoenixlzx/MinoriWiki-theme-semantic-ui)

**Comment by Blacate** [comment]
```ejs
<div class="page-content">
    <%- page.content %>
</div>
```
The `page.content` is generated by remarkable with no className, and I hope it can use `semantic-ui` style, such as `<table class="ui celled table"></table>`.
I used this code to change the style.
```javascript
window.onload = function() {	
	let mainContent = document.querySelector('.page-content');	
	let tables = mainContent.querySelectorAll('table');	
	for(table of tables) {	
		table.className = "ui celled table";	
	}	
}
```
But I don't think it is a good idea as well as [`add table style` commit](https://github.com/phoenixlzx/MinoriWiki/pull/8/commits/843fafccd3b208bb9a5fa92c3e659dba8e978528).
So, some good ideas?

**Comment by phoenixlzx** [comment]
May be modify `MinoriWiki/assets/init/themes/paper/assets/style.css` to add some custom styles?

**Comment by Blacate** [comment]
Emm..
I copied some table-style code from `semantic-ui` to the `style.css`, in this [commit](https://github.com/Blacate/MinoriWiki-theme-semantic-ui/commit/c5dd367945524592d96a500b8d02fe820af46fc4).
It seems to solve the problem....
So, revert this pull request?

**Comment by phoenixlzx** [comment]
I have reverted the changes.

You may open another PR now.

**Pull request merged**
